Ejercicio: resolver el ejercicio 3) anterior con la factorización QR del paquete numpy de la matriz A y verificar resultado $A$: $$A = \begin{bmatrix} 2& -1& 2 \\ 1& 6& -1 \\ 1& 4& 1\end{bmatrix}$$

y utilizarlos para resolver $Ax = B$ con $$B=\begin{bmatrix}7 & -1\\13 & 6\\5 & 7\end{bmatrix}$$

In [6]:
import numpy as np
import pprint
import scipy
import scipy
import scipy.linalg

In [7]:
#Con Factorización QR
A=np.array([[2,-1,2],[1,6,-1],[1,4,1]])
print('A')
pprint.pprint(A)
B=np.array([[7,-1],[13,6],[5,7]])
print('B')
pprint.pprint(B)

A
array([[ 2, -1,  2],
       [ 1,  6, -1],
       [ 1,  4,  1]])
B
array([[ 7, -1],
       [13,  6],
       [ 5,  7]])


In [8]:
Q,R=scipy.linalg.qr(A)

In [9]:
print('Q')
pprint.pprint(Q)
print('R')
pprint.pprint(R)

Q
array([[-0.81649658,  0.56354707, -0.12549116],
       [-0.40824829, -0.71724173, -0.56471022],
       [-0.40824829, -0.40985242,  0.81569255]])
R
array([[-2.44948974, -3.26598632, -1.63299316],
       [ 0.        , -6.5064071 ,  1.43448345],
       [ 0.        ,  0.        ,  1.12942045]])


In [10]:
X=np.linalg.solve(Q,R) #Resuelve el sistema de ecuaciones
print('X')
pprint.pprint(X)

X
array([[ 2.        ,  5.32289624,  0.28662395],
       [-1.38040277,  2.82612964, -2.4120356 ],
       [ 0.30738931,  4.08408703,  0.31611858]])


In [11]:
#Comprobacion que QR es igual a A
print(Q@R)

[[ 2. -1.  2.]
 [ 1.  6. -1.]
 [ 1.  4.  1.]]
