Ejercicio: resolver el ejercicio 3) anterior con la factorización QR del paquete numpy de la matriz A y verificar resultado $A$: $$A = \begin{bmatrix} 2& -1& 2 \\ 1& 6& -1 \\ 1& 4& 1\end{bmatrix}$$

y utilizarlos para resolver $Ax = B$ con $$B=\begin{bmatrix}7 & -1\\13 & 6\\5 & 7\end{bmatrix}$$

In [6]:
import numpy as np
import pprint
import scipy
import scipy
import scipy.linalg

In [7]:
#Con Factorización QR
A=np.array([[2,-1,2],[1,6,-1],[1,4,1]])
print('A')
pprint.pprint(A)
B=np.array([[7,-1],[13,6],[5,7]])
print('B')
pprint.pprint(B)

A
array([[ 2, -1,  2],
       [ 1,  6, -1],
       [ 1,  4,  1]])
B
array([[ 7, -1],
       [13,  6],
       [ 5,  7]])


In [8]:
Q,R=scipy.linalg.qr(A)

In [9]:
print('Q')
pprint.pprint(Q)
print('R')
pprint.pprint(R)

Q
array([[-0.81649658,  0.56354707, -0.12549116],
       [-0.40824829, -0.71724173, -0.56471022],
       [-0.40824829, -0.40985242,  0.81569255]])
R
array([[-2.44948974, -3.26598632, -1.63299316],
       [ 0.        , -6.5064071 ,  1.43448345],
       [ 0.        ,  0.        ,  1.12942045]])


In [10]:
X=np.linalg.solve(Q,R) #Resuelve el sistema de ecuaciones
print('X')
pprint.pprint(X)

X
array([[ 2.        ,  5.32289624,  0.28662395],
       [-1.38040277,  2.82612964, -2.4120356 ],
       [ 0.30738931,  4.08408703,  0.31611858]])


In [11]:
#Comprobacion que QR es igual a A
print(Q@R)

[[ 2. -1.  2.]
 [ 1.  6. -1.]
 [ 1.  4.  1.]]


Ejercicio: resolver los sistemas de ecuaciones lineales $Ax = b$ con la factorización P, LU y verificar resultado
$$1)A = \left[\begin{array}{ccc}
0 &1& -1\\
-2 &4& -1\\
-2 &5& -4
\end{array}
\right],
b=
\left[\begin{array}{c}
3\\
1\\
-2
\end{array}
\right] 
$$
$$2)A \text{ como inciso 1) y } 
b=
\left[\begin{array}{c}
-5\\
7\\
0
\end{array}
\right] 
$$
$$3)A = \left[\begin{array}{cccc}
1 &2& 2\\
2 &5& 7\\
3 &6& 6
\end{array}
\right],
b=
\left[\begin{array}{c}
0\\
0\\
0
\end{array}
\right] 
$$

In [12]:
#Inciso 1
A=scipy.array([[0,1,-1], [-2,4,-1], [-2,5,-4]])
P, L, U =scipy.linalg.lu(A)
print('A:')
pprint.pprint(A)
print('P:')
pprint.pprint(P)
print('L:')
pprint.pprint(L)
print('U:')
pprint.pprint(U)

A:
array([[ 0,  1, -1],
       [-2,  4, -1],
       [-2,  5, -4]])
P:
array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])
L:
array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 1.,  1.,  1.]])
U:
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [ 0.,  0., -2.]])


In [13]:
#Ver que PA = LU
print('Verificacion')
print('L*U:')
pprint.pprint(L@U)
print('P*A')
pprint.pprint(P@A)

Verificacion
L*U:
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [-2.,  5., -4.]])
P*A
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [-2.,  5., -4.]])


In [19]:
#Resolvemos el sistema de ecuaciones
B = scipy.array([3,1,-2])
C = scipy.linalg.solve_triangular(L,P@B,lower=True)
X = scipy.linalg.solve_triangular(U,C)
pprint.pprint(X)

array([10.,  6.,  3.])


In [20]:
#Comprobacion del resultado
print('B:')
pprint.pprint(B)
print('AX:')
pprint.pprint(A@X)

B:
array([ 3,  1, -2])
AX:
array([ 3.,  1., -2.])


In [21]:
#Inciso 2
A=scipy.array([[0,1,-1], [-2,4,-1], [-2,5,-4]])
P, L, U =scipy.linalg.lu(A)
print('A:')
pprint.pprint(A)
print('P:')
pprint.pprint(P)
print('L:')
pprint.pprint(L)
print('U:')
pprint.pprint(U)

A:
array([[ 0,  1, -1],
       [-2,  4, -1],
       [-2,  5, -4]])
P:
array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])
L:
array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 1.,  1.,  1.]])
U:
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [ 0.,  0., -2.]])


In [22]:
#Ver que PA = LU
print('Verificacion')
print('L*U:')
pprint.pprint(L@U)
print('P*A')
pprint.pprint(P@A)

Verificacion
L*U:
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [-2.,  5., -4.]])
P*A
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [-2.,  5., -4.]])


In [23]:
#Resolvemos el sistema de ecuaciones
B = scipy.array([-5,7,0])
C = scipy.linalg.solve_triangular(L,P@B,lower=True)
X = scipy.linalg.solve_triangular(U,C)
pprint.pprint(X)

array([-12.,  -4.,   1.])


In [24]:
#Comprobacion del resultado
print('B:')
pprint.pprint(B)
print('AX:')
pprint.pprint(A@X)

B:
array([-5,  7,  0])
AX:
array([-5.,  7.,  0.])


In [35]:
#Inciso 3 Método Normal
A = np.array([[2,1,1], [2,5,7], [3,6,6]])
B = np.array([0,0,0])
print('A:')
pprint.pprint(A)
print('B:')
pprint.pprint(B)

A:
array([[2, 1, 1],
       [2, 5, 7],
       [3, 6, 6]])
B:
array([0, 0, 0])


In [36]:
X=np.linalg.solve(A,B)
print('X:')
pprint.pprint(X)

X:
array([ 0., -0.,  0.])


In [37]:
#Comprobando Resultado
print('B:')
pprint.pprint(B)
print('AX:')
pprint.pprint(A@X)

B:
array([0, 0, 0])
AX:
array([0., 0., 0.])
