In [1]:
#numpy Modle
#Creating an array
from numpy import array
a=array([[3.0,-6.0],[5.0,7.0]])
print(a)

[[ 3. -6.]
 [ 5.  7.]]


In [2]:
from numpy import *
print(arange(3,15,3))

[ 3  6  9 12]


In [3]:
print(ones(4))

[1. 1. 1. 1.]


In [4]:
from numpy import *
a=zeros((3,3),int)
print(a)
a[0]=[5,70,45]
a[1,1]=6
a[2,0:2]=[54,67]
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 5 70 45]
 [ 0  6  0]
 [54 67  0]]


In [5]:
#Operations on Arrays
from numpy import array
z=array([5.5,1.0,4.6,15.0])
print(z/3.0)
print(sqrt(z))
print(cos(z))

[1.83333333 0.33333333 1.53333333 5.        ]
[2.34520788 1.         2.14476106 3.87298335]
[ 0.70866977  0.54030231 -0.11215253 -0.75968791]


In [6]:
from numpy import array
from math import sqrt
y=array([45.0,67.0,1])
print(sqrt(y[0]))

6.708203932499369


In [7]:
from numpy import *
C=array([[1.5,5.9,0.0],[7.1,4.6,8.0],[12.0,34,2.9]])
print(diagonal(C,1 ))
print(trace(C))

[5.9 8. ]
9.0


In [8]:
#Identity Matrix
print(identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
